version: "0.1"
services:
  web:
    image: webapp
    ports:
      - "8080:80"
    env_file:
      - ..\.env
  admin:
    image: adminwebapp
    ports:
      - "8081:80"
    env_file:
      - ..\.env
  backend:
    image: backend
    ports: 
      - "8082:80"
    env_file:
      - ..\.env
