name: Admin Web App Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: aispeechtotext.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker pull aispeechtotext.azurecr.io/rag-adminwebapp-fork:latest || true;
        docker build . --file web/docker/AdminWebApp.Dockerfile --cache-from aispeechtotext.azurecr.io/rag-adminwebapp-fork:latest --tag aispeechtotext.azurecr.io/rag-adminwebapp-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag aispeechtotext.azurecr.io/rag-adminwebapp-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER aispeechtotext.azurecr.io/rag-adminwebapp-fork:latest;
        docker push aispeechtotext.azurecr.io/rag-adminwebapp-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push aispeechtotext.azurecr.io/rag-adminwebapp-fork:latest;
