name: Backend Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Docker Login
      uses: docker/login-action@v2.2.0
      with:
        registry: cscicontainer.azurecr.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:
        docker pull cscicontainer.azurecr.io/rag-backend-fork:latest || true;
        docker build . --file web/docker/Backend.Dockerfile --cache-from cscicontainer.azurecr.io/rag-backend-fork:latest --tag cscicontainer.azurecr.io/rag-backend-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag cscicontainer.azurecr.io/rag-backend-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER cscicontainer.azurecr.io/rag-backend-fork:latest;
        docker push cscicontainer.azurecr.io/rag-backend-fork:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push cscicontainer.azurecr.io/rag-backend-fork:latest;
        