# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: DEV - build and release api

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
        
  deploy-to-dev:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: prontocontainers.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    - run: |
        docker build . -t prontocontainers.azurecr.io/pronto-fontend -f ./docker/Frontend.Dockerfile
        docker push prontocontainers.azurecr.io/pronto-fontend

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1EC8C71974184A14A7AFB91F4676FE53 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C68709E83D0B4B41815059C3FCED7A93 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_991984B989F44817B0925FB42F086658 }}                        
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-dsfb352ephiyu'
        images:  prontocontainers.azurecr.io/pronto-fontend

  deploy-to-prod:
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/main'
    environment:
      name: 'prod'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master

    - uses: azure/docker-login@v1
      with:
        login-server: prontocontainers.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}


    - run: |
        docker build . -t prontocontainers.azurecr.io/pronto-fontend -f ./docker/Frontend.Dockerfile
        docker push prontocontainers.azurecr.io/pronto-fontend

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_40F8872A222540F4A90B1A3C4BDD09F6 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B64A0DAF04094E0EBC57C3F69091FD99 }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_DE9C0EC07B6947CBA9333317F147DAA5 }}                      
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'web-6fzbc32vpqwni'
        images:  prontocontainers.azurecr.io/pronto-fontend      
