name: DEV - admin - build container and release
on:
  push:
    branches:
      - development
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT 
    steps:
    # checkout the repo
    - name: 'Checkout Github Action'
      uses: actions/checkout@master
    - uses: azure/docker-login@v1
      with:
        login-server: prontocontainers.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t prontocontainers.azurecr.io/pronto-admin -f ./docker/Admin.Dockerfile
        docker push prontocontainers.azurecr.io/pronto-admin

    - name: Login to Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_73A3FE74C38349A5BB52C79AFAC5BF96 }}
        tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6F3AF3E2BF5949E79CC51223797DA85A }}
        subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E61CF904F8FF4E4FA283B10496C7B811 }}
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      id: deploy-to-webapp
      with:
        app-name: 'web-6fzbc32vpqwni-admin'
        images:  prontocontainers.azurecr.io/pronto-admin
        
